reintroduce XL logic into _readSort() to make Sort pushdown work
During merge, the XL portable_input infrastructure got removed from
_readSort(), resulting in errors like this

    ERROR: did not find '}' at end of input node

when running queries with Sort push-down. Fixed by reintroducing
the coding from 9.5 branch, however this is hardly the last bug
in node functions.