Remove 'unrecognized node type' errors from expected output
The expected output for two regression suites ("with" and "rules")
included error messages like this:

    ERROR: unrecognized node type: %d

which is clearly a mistake, and just hides an error in the code.