add T_GroupingFunc to pgxc_shippability_walker
Planning grouping sets queries with grouping() function failed with

    ERROR:  XX000: unrecognized node type: 307
    LOCATION:  pgxc_shippability_walker, pgxcship.c:1199
    STATEMENT:  select grouping(a, b), count(*) from t1
                group by grouping sets ((a), (b));

We simply inspect arguments of the grouping() function, although
that probably is not necessary - it can only reference grouping
expressions, which are checked as part of other nodes.